import Head from 'next/head'
import type { GetStaticProps} from 'next'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import homeStyles from '../styles/Home.module.css'
import { getSortedPostData } from '../lib/post'
import Link from 'next/link'


const Home = ({ allPostsData }:{
  allPostsData: {
    date: string
    title: string
    id: string
  }[]
}) => {
  return (
    <div>
      <Head>
        <title>sarang kim</title>
        <meta name="description" content = "Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <section className={homeStyles.headingMd}>
        <p>[sarang introduction]</p>
        <p>
          (This is a sample website)
        </p>
      </section>
      <section className={`${homeStyles.headingMd} ${homeStyles.padding1px}`}>
        <h2 className={homeStyles.headingLg}>Blog</h2>
        <ul className={homeStyles.list}>
          {allPostsData.map(({id, title, date}) =>
          <li className='{homeStyles.listItem}' key ={id}>
            <Link href={`/posts/${id}`}>
            <a> {title} </a> <br/>
            </Link>
            <br />
            <small className='{homeStyles.lightText}'>
              {date}
            </small>
          </li>
          )}
        </ul>
      </section>
    </div>
  )
}
export default Home

export const getStaticProps: GetStaticProps = async () =>{
  const allPostsData = getSortedPostData();
  return {
    props: {
      allPostsData
    }
  }
}
