import Head from 'next/head'
import type {NextPage} from 'next'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import homeStyles from '../styles/Home.module.css'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>sarang kim</title>
        <meta name="description" content = "Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <section className={homeStyles.headingMd}>
        <p>[sarang introduction]</p>
        <p>
          (This is a sample website)
        </p>
      </section>
      <section className={`${homeStyles.headingMd} ${homeStyles.padding1px}`}>
        <h2 className={homeStyles.headingLg}>Blog</h2>
        <ul className={homeStyles.list}>

        </ul>
      </section>
    </div>
  )
}
export default Home
